#!/bin/bash

LOCK_FILE="$HOME/.biglinux-shell-changed"

if [ ! -f "$LOCK_FILE" ]; then

    biglinux-change-default-shell bash-power
    mkdir -p ~/.cache/blesh/dummy
    touch ~/.cache/blesh/dummy/decode.bind.dummy.bind
    touch ~/.cache/blesh/dummy/k
    
fi